import { Button } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Next.js Routing and Next Link</h1>
        <Button>
          <Link href="/events">Explore Events!</Link>
        </Button>

        <Button>
          <Link href="/users">See All Users</Link>
        </Button>
      </main>
    </div>
  );
}
